### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi there I updated translations :smile: 
Notify me if you make other changes that I have to translate too!

Note: Don't forget to add _( ) when you add new strings to make them translatable. Please use the ellipsis symbol instead of three dots, as recommended by elementary HIG.

### CODE REVIEW

**Comment by dcharles525** [comment]
@NathanBnm Got it! I am still working on some stuff with the new limits feature but when I finish I will add the _() to everything. 

I will comment back here when I make sure everything is stable. Thanks for the translations!

**Comment by dcharles525** [comment]
I think I've fixed everything up, feel free to update anything that may have gotten out of sync.

**Comment by NathanBnm** [comment]
Great, I'm just going to check that!

**Comment by NathanBnm** [comment]
Actually I updated translations but notifications aren't working anymore. The mode switch button in the time limits dialog doesn't do anything, it stays to off (it doesn't remember the state) and there is an error in the console.

**Comment by dcharles525** [comment]
hmm, ok I will fix those issues, thanks again for all your work!

**Comment by dcharles525** [comment]
Ah @NathanBnm can you delete the database in home/config/crypt/. I think this pull request was before I fixed up other database stuff so it generated a incomplete database. 

That should fix your problem.

**Comment by NathanBnm** [comment]
@dcharles525  I'm can't find it. I have no config folder into home folder. My app is still broken.

**Comment by dcharles525** [comment]
@NathanBnm There should be somewhere on your system where "CryptStore" is saved. This is the sqllite database and its safe to delete once found and will reset your installation of crypt.

**Comment by NathanBnm** [comment]
I'll try tout find thar then

**Comment by NathanBnm** [comment]
I found it, it was in `/home/username/.config` :smile:

**Pull request merged**
